---
- name: Setup DBserver
  hosts: dbsrvgrp
  become: yes
  vars:
    dbname: groups
    dbuser: devops
    dbpass: admin123
  tasks:
    - debug: 
        var: dbname

    - debug:
        msg: "Value of dbuser is {{dbuser}}"

    - name: Install MySQL server
      yum:
         name: mariadb-server
         state: present
         
    - name: Install Python MySQL 
      yum:
         name: MySQL-python
         state: present

    - name: Start & Enable maridb service
      service:
         name: mariadb
         state: started
         enabled: yes

    - name: Create a new database with name 'accounts'
      mysql_db:
        name: "{{dbname}}"
        state: present

    - name: Create database user with name 'admin' 
      mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        state: present
