apiVersion: v1
kind: Pod
metadata:
  name: nginx
  # the name space can be specified like this
  namespace: shinakube
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
