pipeline {
    agent any

    tools {
        maven "MAVEN3"  // the name of the tools in the jenkins configuration
        jdk "OracleJDK8"  // the LHS is an arbitrary name, make sure the RHS correspond to the tools name
    }

    stages {
        stage('Fetch Code') {
            steps {
                git branch: 'vp-rem', url: 'https://github.com/adesinna/vprofile-project.git'

            }
        }

        stage('Build') {
            steps {
                sh 'mvn install -DskipTests'
            }

            post {
                success {
                    echo 'Now Archiving it... '
                    archiveArtifacts artifacts: '**/target/*.war'

                }
            }

        }

        stage('Unit test') {
            steps {
                sh 'mvn test'
            }

        }

        stage('Checkstyle Analysis'){
            steps{
                sh 'mvn checkstyle:checkstyle'
            }
        }


    }
}