apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  # key value type data
  player_initial_lives: "3" # a string value
  ui_properties_file_name: "user-interface.properties" # properties is  file in user-interface

  # file-like key and they would be stored in a file in the container

  game.properties: |   # this is multiline content that will be stored in the file
    enemy.types=aliens,monsters   
    player.maximum-lives=5

  user-interface.properties: |  # this is multiline content that will be stored in the file
    color.good=purple
    color.bad=yellow
    allow.textmode=true 
  



