apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort # the service type
  ports:
    - targetPort: 80 # the port of the pod
      port: 80 # the port of the service
      nodePort: 30008 # the port of the node that is opened to the external world
  selector:
    app: myapp
