apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080 # pods port
      port: 80 # service port
      protocol: TCP
  selector:
    app: vproapp