apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  ports:
  - port: 80 # frontend
    targetPort: vproapp-port # backend
    protocol: TCP
  selector:
    app: vproapp
  type: LoadBalancer # use load balancer