apiVersion: v1
kind: Service
metadata:
  name: vprocache01
spec:
  ports:
  - port: 11211 # frontend port for the service
    targetPort: vpromc-port #backend port
    protocol: TCP
  selector:
    app: vpromc
  type: ClusterIP # internal connections