pipeline {
    agent any

    environment {
        DOCKERHUB_USERNAME = "adesinna"
        APP_NAME = "movie-project"
        IMAGE_TAG = "${BUILD_NUMBER}"
        IMAGE_NAME = "${DOCKERHUB_USERNAME}/${APP_NAME}"
        REGISTRY_CREDS = 'dockerhub'
    }

    stages {
        stage('Clean up workspace') {
            steps {
                cleanWs() //it cleans the workspace
            }
        }

        stage('Checkout SCM') {
            steps {
                git credentialsId: 'github', url: 'https://github.com/adesinna/frontend-project.git', branch: 'master'
            }
        }

        stage('Build Image') {
            steps {
                script {
                    docker_image = docker.build("${IMAGE_NAME}:${IMAGE_TAG}")
                }
            }
        }

        stage('Push Image') {
            steps {
                script {
                    docker.withRegistry('',REGISTRY_CREDS){
                        docker_image.push("$BUILD_NUMBER")
                        docker_image.push('latest')
                    }
                }
            }
        }

        stage('Remove Images'){
            steps{
                sh "docker rmi ${IMAGE_NAME}:${IMAGE_TAG}"
                sh "docker rmi ${IMAGE_NAME}:latest"
            }
        }

        stage("Update the deployment on repo") {
            steps{
                script{
                    sh """
                        sed -i 's/${APP_NAME}.*/${APP_NAME}:${IMAGE_TAG}/g' deployment.yaml
                        git config --global user.name "adesinna"
                        git config --global user.email "aladesaea@yahoo.com"
                        git commit -m "updated deployment"
                       """

                       withCredentials([gitUsernamePassword(credentialsId: 'github', gitToolName: 'Default')]) {

                       sh "git push https://github.com/adesinna/frontend-project.git master"
                       }


                }
            }
        }

    }
}
