apiVersion: v1 
kind: Pod
metadata:
  name: test-pod
  labels:
    tester: adesina
spec:
  containers:
  - name: apache
    image: apache
      # mount the volume here
    volumeMounts:
    # name of the volume you want to map, host volume name
    - name: test-volume
      # where you want to mount
      mountPath: /test-pd 
  volumes:
  # this is for the host
  - name: test-volume
    hostPath:
      path: /data
    # to make sure it creates it if it is not present
      type: DirectoryOrCreate

    