---
- name: Setup DBserver
  hosts: dbservergroup
  become: yes

  tasks:
    - debug:
        var: first_name

    - debug:
        msg: "{{ second_name }}"

    - name: create a user
      user:             # this is how to create users
        name: "{{ first_name }}"
        comment: "{{ second_name }}"
      register: OUTPUT  # stores the output of the creation
    - debug:
        var: OUTPUT

    - debug:
        var: OUTPUT.comment # getting one of th attributes of the output





