Vagrant.configure("2") do |config|

  config.vm.define "scriptbox" do |scriptbox|
    scriptbox.vm.box = "jacobw/fedora35-arm64"
	scriptbox.vm.network "private_network", ip: "192.168.10.12"
	scriptbox.vm.synced_folder "./data", '/vagrant_data'
	scriptbox.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"

   end
  end

  config.vm.define "web01" do |web01|
    web01.vm.box = "jacobw/fedora35-arm64"
	web01.vm.network "private_network", ip: "192.168.10.13"
  end

  config.vm.define "web02" do |web02|
    web02.vm.box = "jacobw/fedora35-arm64"
	web02.vm.network "private_network", ip: "192.168.10.14"
  end

   config.vm.define "web03" do |web03|
    web03.vm.box = "spox/ubuntu-arm"
        web03.vm.network "private_network", ip: "192.168.10.15"
  end
end
